conveyal/r5

src/main/java/com/conveyal/r5/api/util/SegmentPattern.java
src/main/java/com/conveyal/r5/profile/McRaptorSuboptimalPathProfileRouter.java

So that it finds only trips that actually run on wanted day.
This also speeds up McRaptor from 100 ms to 25 ms in my small graph.
Fixes #110

McRaptorSuboptimal uses service times when routing

---

pom.xml
src/main/java/com/conveyal/r5/analyst/scenario/AddTrips.java
src/main/java/com/conveyal/r5/analyst/scenario/Scenario.java
src/main/java/com/conveyal/r5/transit/DuplicateFeedException.java
src/main/java/com/conveyal/r5/transit/RouteInfo.java
src/main/java/com/conveyal/r5/transit/TransitLayer.java
src/main/java/com/conveyal/r5/transit/TransportNetwork.java
src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java
src/main/java/com/conveyal/r5/transit/TripSchedule.java
src/test/java/com/conveyal/r5/analyst/scenario/FakeGraph.java
src/test/java/com/conveyal/r5/transit/FrequencyRandomOffsetsTest.java

Switch to the new GTFS lib which uses MapDB for all objects. Also check checksums when applying scenarios.

Switch to new GTFS Lib

---

src/main/java/com/conveyal/r5/analyst/IsochroneFeature.java
src/main/java/com/conveyal/r5/point_to_point/PointToPointRouterServer.java
src/main/java/com/conveyal/r5/profile/ProfileRequest.java
src/main/java/com/conveyal/r5/profile/RepeatedRaptorProfileRouter.java
src/main/java/com/conveyal/r5/streets/LinkedPointSet.java

A few changes here:
* Fix bug with incorrect speeds being used for propagation that caused extra holes and shells in car isochrones
* Simply outer rings to make finding the relevant rings for holes work
* Get rid of really small rings

Faster isochrone generation

---

src/main/java/com/conveyal/r5/analyst/broker/BrokerHttpHandler.java
src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java

Send content types back to client.

proper content types for high priority broker responses, fixes #229.

---

src/main/java/com/conveyal/r5/analyst/broker/BrokerHttpHandler.java
src/main/java/com/conveyal/r5/analyst/error/ScenarioApplicationException.java
src/main/java/com/conveyal/r5/analyst/error/TaskError.java
src/main/java/com/conveyal/r5/analyst/scenario/AddTrips.java
src/main/java/com/conveyal/r5/analyst/scenario/AdjustDwellTime.java
src/main/java/com/conveyal/r5/analyst/scenario/AdjustFrequency.java
src/main/java/com/conveyal/r5/analyst/scenario/AdjustSpeed.java
src/main/java/com/conveyal/r5/analyst/scenario/Modification.java
src/main/java/com/conveyal/r5/analyst/scenario/RemoveStops.java
src/main/java/com/conveyal/r5/analyst/scenario/RemoveTrips.java
src/main/java/com/conveyal/r5/analyst/scenario/Reroute.java
src/main/java/com/conveyal/r5/analyst/scenario/Scenario.java
src/main/java/com/conveyal/r5/analyst/scenario/SetPhase.java
src/main/java/com/conveyal/r5/publish/StaticMetadata.java
src/main/java/com/conveyal/r5/transit/TransportNetwork.java
src/test/java/com/conveyal/r5/analyst/scenario/RemoveStopsTest.java

This also adds the ability to return warnings to the frontend.

Remove time when removing stops

---

src/main/java/com/conveyal/r5/analyst/GridComputer.java
src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java
src/main/java/com/conveyal/r5/analyst/cluster/GridResultConsumer.java
src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java
src/main/java/com/conveyal/r5/profile/Propagater.java
src/main/java/com/conveyal/r5/profile/RaptorState.java
src/main/java/com/conveyal/r5/profile/RaptorWorker.java
src/main/java/com/conveyal/r5/publish/StaticComputer.java
src/main/java/com/conveyal/r5/publish/StaticServer.java

@abyrd not ready for merge but please review.

New raptor worker

---

src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java

This fixes the nasty bug we found in the Fast RAPTOR worker during the bootstrapping exercises. While we're planning to merge those soon we wanted to get these into master ASAP.

Fix fast raptor bug

---

src/main/java/com/conveyal/r5/analyst/DualGridStatisticComputer.java
src/main/java/com/conveyal/r5/analyst/GridBounds.java
src/main/java/com/conveyal/r5/analyst/GridComputer.java
src/main/java/com/conveyal/r5/analyst/TravelTimeSurfaceComputer.java
src/main/java/com/conveyal/r5/analyst/cluster/AccessGridWriter.java
src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java
src/main/java/com/conveyal/r5/analyst/cluster/GenericClusterRequest.java
src/main/java/com/conveyal/r5/analyst/cluster/TravelTimeSurfaceRequest.java
src/main/java/com/conveyal/r5/analyst/scenario/GridStatisticComputer.java
src/main/java/com/conveyal/r5/api/util/LegMode.java
src/main/java/com/conveyal/r5/common/JsonUtilities.java
src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java
src/main/java/com/conveyal/r5/profile/PerTargetPropagater.java
src/main/java/com/conveyal/r5/profile/ProfileRequest.java

This allows us to get travel times as Access Grids rather than only in Browsochrones format.

New analysis interface

---

src/main/java/com/conveyal/r5/analyst/broker/BrokerHttpHandler.java
src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java
src/main/java/com/conveyal/r5/profile/PerTargetPropagater.java

We should merge this and cut 2.2.1, and probably 2.2.0 from production since it gives wrong results. However, this is quite a bit slower and takes a really long time to propagate in the Netherlands (40s for the whole country).

fix issue with PerTargetPropagater that caused incorrect results.

---

.travis.yml

Reinstate javadoc builds to javadoc.conveyal.com

Fix javadoc

---

src/main/java/com/conveyal/r5/analyst/GridComputer.java
src/main/java/com/conveyal/r5/analyst/TravelTimeSurfaceComputer.java
src/main/java/com/conveyal/r5/point_to_point/builder/PointToPointQuery.java
src/main/java/com/conveyal/r5/streets/EdgeStore.java
src/main/java/com/conveyal/r5/streets/ParkRideRouter.java
src/main/java/com/conveyal/r5/streets/StreetLayer.java
src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java

I added changes but I can't test.
I'm not sure what to do with sr::getTravelTimeToVertex, since function returns time, but it seems that distance is expected.
ParkRideRouter returns travel time only to stops not to all vertices, since it doesn't actually route from P+R to stops. Because stops are found during graph build time.

Park ride analyst support

---

src/main/java/com/conveyal/r5/analyst/Grid.java

Needed for weighted averaging in frontend.

allow rasterizing polygon and returning weights relative to pixels.

---

.travis.yml
README.md
src/main/java/com/conveyal/r5/analyst/Grid.java
src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java
src/main/java/com/conveyal/r5/analyst/broker/WorkerStartupScriptTestHook.java
src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java
src/main/java/com/conveyal/r5/analyst/cluster/RegionalTask.java
src/main/java/com/conveyal/r5/labeling/LevelOfTrafficStressLabeler.java
src/main/java/com/conveyal/r5/labeling/TraversalPermissionLabeler.java
src/main/java/com/conveyal/r5/point_to_point/builder/PointToPointQuery.java
src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java
src/main/java/com/conveyal/r5/streets/EdgeStore.java
src/main/java/com/conveyal/r5/streets/ParkRideRouter.java
src/main/java/com/conveyal/r5/streets/StreetLayer.java
src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java
src/main/resources/worker.sh

So it will merge cleanly back to master.

Merge master into remove cruft

---

src/main/java/com/conveyal/r5/analyst/scenario/AddTrips.java
src/test/java/com/conveyal/r5/analyst/scenario/AddTripsTest.java

This still needs an automated test.

Add exact times support to add trips (#290).

---

src/main/java/com/conveyal/r5/transit/TransitLayer.java

Loading feeds like the MBTA or LA Metro takes an extra ~5 minutes because this warning is printed for all zero-duration hops, which are prevalent when feed maintainers round stop_times arrival/departure times to the nearest minute.
We could eventually build in more logic to check whether the implied speeds are reasonable.  But for now, this speeds things up, and still gives a warning that would raise a red flag for feeds that don't have rounded stop_times.

perf(logging): stop printing all zero-length hop warnings

---

src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java

Fixes #354 
Needed for https://github.com/conveyal/analysis-ui/pull/529

Filter patterns by requested modes

---

src/main/java/com/conveyal/r5/analyst/TravelTimeSurfaceReducer.java

Work in progress on a few walk/bike/access mode bugs

Misc. fixes for walk and bike

---

src/main/java/com/conveyal/r5/analyst/PointSet.java
src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java
src/main/java/com/conveyal/r5/profile/PerTargetPropagater.java
src/main/java/com/conveyal/r5/profile/ProfileRequest.java
src/main/java/com/conveyal/r5/streets/LinkedPointSet.java
src/main/java/com/conveyal/r5/streets/Split.java

Fixes a couple problems:
1. non-transit analyses too fast by a factor of 60 (#347)
2. biking access too slow by a factor of 60 (#349)
3. no cost to access network, leading to long swims (#337)
Adds steps to set egress mode (but this is not yet fully implemented)

Linking fixes

---

src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java

perf(frequency): only perform frequency search when needed

---

pom.xml
src/main/java/com/conveyal/r5/analyst/BootstrappingTravelTimeReducer.java
src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java
src/main/java/com/conveyal/r5/analyst/TravelTimeSurfaceReducer.java
src/main/java/com/conveyal/r5/analyst/cluster/AccessGridWriter.java
src/main/java/com/conveyal/r5/analyst/cluster/Origin.java
src/main/java/com/conveyal/r5/profile/PerTargetPropagater.java
src/main/java/com/conveyal/r5/profile/ProfileRequest.java
src/main/java/com/conveyal/r5/streets/EdgeStore.java
src/main/java/com/conveyal/r5/streets/LinkedPointSet.java
src/main/java/com/conveyal/r5/streets/PointSetTimes.java
src/main/java/com/conveyal/r5/streets/Split.java

These changes are all optimizations that skip unnecessary calculation, especially useful for large regional analyses in places with a lot of water.

Analysis Worker Optimizations

---

.travis.yml
pom.xml
src/main/java/com/conveyal/r5/analyst/BootstrappingTravelTimeReducer.java
src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java
src/main/java/com/conveyal/r5/analyst/TravelTimeSurfaceReducer.java
src/main/java/com/conveyal/r5/analyst/broker/Broker.java
src/main/java/com/conveyal/r5/analyst/broker/BrokerHttpHandler.java
src/main/java/com/conveyal/r5/analyst/broker/Job.java
src/main/java/com/conveyal/r5/analyst/cluster/AccessGridWriter.java
src/main/java/com/conveyal/r5/analyst/cluster/GridResultAssembler.java
src/main/java/com/conveyal/r5/analyst/cluster/Origin.java
src/main/java/com/conveyal/r5/common/Util.java
src/main/java/com/conveyal/r5/point_to_point/builder/PointToPointQuery.java
src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java
src/main/java/com/conveyal/r5/profile/PerTargetPropagater.java
src/main/java/com/conveyal/r5/profile/ProfileRequest.java
src/main/java/com/conveyal/r5/streets/EdgeStore.java
src/main/java/com/conveyal/r5/streets/LinkedPointSet.java
src/main/java/com/conveyal/r5/streets/PointSetTimes.java
src/main/java/com/conveyal/r5/streets/Split.java
src/main/java/com/conveyal/r5/streets/StreetRouter.java
src/main/java/com/conveyal/r5/streets/TarjanIslandPruner.java
src/main/java/com/conveyal/r5/streets/TravelTimeCalculator.java
src/test/java/com/conveyal/r5/streets/TimeDependentRoutingTest.java

There are some improvements to how the backend works (e.g. using setLength in https://github.com/conveyal/r5/pull/372) that we should merge into master now, even if we're not ready for a tagged release of the worker/routing functionality.

Recent changes into master

---

pom.xml

Pull changes back into active development branch (`dev`) after release off of `master`

 Prepare next development iteration 4.0.0-SNAPSHOT

---

src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java

I tested this using the example described in #407, and it worked.
We should probably do a bit more testing to make sure there are not unintended side effects.

Disallow boarding/alighting when pickup/drop_off type is none

---

pom.xml

Update spark-core to 2.7.2 to address security vulnerability

---

.travis.yml

These additional commands are required to make commits and merge master into dev

Update travis command for maven-semantic-release

---

src/main/java/com/conveyal/r5/analyst/TravelTimeReducer.java
src/main/java/com/conveyal/r5/profile/ProfileRequest.java

Mark destinations exceeding maxTripDurationMinutes UNREACHED

---

src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java

See comment in code: the underlying framework will not accept small numbers of threads, especially on container-based infrastructure with lots of (inaccessible) cores.
I would like to get this change into an R5 bugfix release as soon as we can, so I can update the dependency in analysis-backend, and get analysis-backend tests runing in the CI environment.

Remove limit on number of single point http handler threads

---

src/main/java/com/conveyal/r5/analyst/scenario/AddTrips.java
src/main/java/com/conveyal/r5/transit/TripSchedule.java

We haven't yet determined a fix for #568, but it can go here when we do.

Fix for exact-times add-trip modifications

---

pom.xml
src/main/java/com/conveyal/r5/analyst/scenario/AdjustFrequency.java

- Includes a clearer error message (for conveyal/analysis-ui#1008)
- Bumps gtfs-lib to version with fix for #579

GTFS Patches

---

src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java

Fixes #636, and includes a minor optimization

Transfer Cleanup

---

src/main/java/com/conveyal/analysis/components/HttpApi.java
src/main/java/com/conveyal/analysis/components/TaskScheduler.java
src/main/java/com/conveyal/analysis/components/eventbus/EventBus.java
src/main/java/com/conveyal/analysis/components/eventbus/EventHandler.java

This PR updates the EventHandler interface so event handlers announce their own characteristics, allowing simpler registration.

refactor EventBus

---

src/main/java/com/conveyal/r5/transit/TransitLayer.java

Use "[new]" as stopId in path details for stops added in scenarios

---

src/main/java/com/conveyal/data/census/LodesSource.java
src/test/java/com/conveyal/data/census/IntegrationTest.java

"Due to a delay in input files, Firm Age and Firm Size are currently unavailable for 2018. " - https://lehd.ces.census.gov/data/lodes/LODES7/LODESTechDoc7.5.pdf
Fixes https://github.com/conveyal/analysis-ui/issues/1101

Skip missing LODES fields

---

src/main/java/com/conveyal/analysis/controllers/BrokerController.java

This errors will bubble up to the user so it's useful to have specific error messages and not just "NullPointerException"s.

Add error messages for `checkNotNull` in the BrokerController

---

src/main/java/com/conveyal/r5/streets/EgressCostTable.java
src/main/java/com/conveyal/r5/transit/TransitLayer.java

This should fix issue #781. Looks good so far in tests.

Set linking distance for non-scenario egress tables

---

README.md
src/main/java/com/conveyal/analysis/components/TaskScheduler.java
src/main/java/com/conveyal/analysis/controllers/BundleController.java
src/main/java/com/conveyal/analysis/controllers/GtfsController.java
src/main/java/com/conveyal/analysis/controllers/OpportunityDatasetController.java
src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java
src/main/java/com/conveyal/analysis/controllers/UserActivityController.java
src/main/java/com/conveyal/analysis/datasource/derivation/AggregationAreaDerivation.java
src/main/java/com/conveyal/analysis/models/AggregationArea.java
src/main/java/com/conveyal/analysis/models/DataSourceValidationIssue.java
src/main/java/com/conveyal/analysis/models/OpportunityDataset.java
src/main/java/com/conveyal/gtfs/GTFSCache.java
src/main/java/com/conveyal/gtfs/GTFSFeed.java
src/main/java/com/conveyal/gtfs/error/ForbiddenFieldError.java
src/main/java/com/conveyal/gtfs/model/Calendar.java
src/main/java/com/conveyal/gtfs/model/CalendarDate.java
src/main/java/com/conveyal/gtfs/model/Entity.java
src/main/java/com/conveyal/gtfs/model/Stop.java
src/main/java/com/conveyal/gtfs/validator/PostLoadValidator.java
src/main/java/com/conveyal/r5/analyst/scenario/IndexedPolygonCollection.java
src/main/java/com/conveyal/r5/common/GeometryUtils.java

Merging to create dated commit in master that we will use in Cluster. But, we are not tagging, since we do not plan to update the recommended R5 version.

2022-07 Release

---

.github/workflows/codeql-analysis.yml
src/main/java/com/conveyal/r5/streets/StreetRouter.java
src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java

A free service provided by Github, this action "runs GitHub's industry-leading semantic code analysis engine, CodeQL, against a repository's source code to find security vulnerabilities. It then automatically uploads the results to GitHub so they can be displayed in the repository's security tab. CodeQL runs an extensible set of [queries](https://github.com/github/codeql), which have been developed by the community and the [GitHub Security Lab](https://securitylab.github.com/) to find common vulnerabilities in your code."

Add CodeQL Analysis Github Action

---

src/main/java/com/conveyal/r5/analyst/cluster/PathResultSummary.java

Return correct route info for path display

---

src/main/java/com/conveyal/analysis/datasource/ShapefileDataSourceIngester.java

Fixes #833. I believe the true point of the assertion was not to check the envelope, but to provide a sink for the features in the shapefile, looping over all of them such that the whole file is decoded and projected and ensuring it's a valid usable file.
This did highlight that the envelope coming from `reader.wgs84Bounds()` does not necessarily contain all the points (particularly if the axes of the source projection are not parallel to those of WGS84), so I just built up the WGS84 envelope using the decoded and transformed points.

Grow envelope from projected coords

---

src/main/java/com/conveyal/r5/analyst/cluster/PathResult.java
src/main/java/com/conveyal/r5/transit/TransitLayer.java
src/main/java/com/conveyal/r5/transit/path/RouteSequence.java

Supersedes https://github.com/conveyal/r5/pull/927 (where we encountered merge problems on GitHub)

Add feed id column to path results (sequel)
