conveyal/r5

pom.xml, src/main/java/com/conveyal/r5/analyst/broker/Broker.java, src/main/java/com/conveyal/r5/analyst/cluster/JobSimulator.java, src/main/java/com/conveyal/r5/common/JsonUtilities.java, src/main/java/com/conveyal/r5/model/json_serialization/JavaLocalDateSerializer.java, src/main/java/com/conveyal/r5/model/json_serialization/JodaLocalDateDeserializer.java, src/main/java/com/conveyal/r5/model/json_serialization/JodaLocalDateSerializer.java, src/main/java/com/conveyal/r5/profile/ProfileRequest.java, src/main/java/com/conveyal/r5/transit/TransitLayer.java, src/main/java/com/conveyal/r5/transit/TransitRouter.java, src/test/java/com/conveyal/r5/analyst/core/LocalDateSerialization.java
It removes all joda calls in R5 and also from calls to gtfs-lib since it depends on conveyal/gtfs-lib#5 to be merged.
It can be merged if there are no problems with removing joda in gtfs-lib otherwise #21 can be merged.
=> Joda complete removal

src/main/java/com/conveyal/r5/point_to_point/PointToPointRouterServer.java, src/main/java/com/conveyal/r5/profile/StreetPath.java, src/main/java/com/conveyal/r5/streets/EdgeStore.java, src/main/java/com/conveyal/r5/streets/StreetRouter.java
Because duration now exists in State current time is redundant so it is
removed.
=> Remove time from State

src/main/java/com/conveyal/r5/point_to_point/builder/PointToPointQuery.java, src/main/java/com/conveyal/r5/profile/McRaptorSuboptimalPathProfileRouter.java
So that filtering is done during the search itself instead at the end.
It skips stops and trips which don't have wheelchair support.
It also skips patterns that don't have transitModes that are requested.
Working on #109.
It seems to be working OK. Some different trips are found then when afterwards filtering is used. But it takes a little more time in raptor.
I added wheelchair checks on the same places that service checks were made. And I added one on stops.
@mattwigway: Could you please check if it is OK?
Then I'll remove afterwards filtering and it can be merged.
=> Move wheelchair filtering into raptor algoritm

src/main/java/com/conveyal/r5/api/util/StreetSegment.java, src/main/java/com/conveyal/r5/point_to_point/builder/PointToPointQuery.java, src/main/java/com/conveyal/r5/profile/StreetPath.java, src/main/java/com/conveyal/r5/streets/EdgeStore.java, src/main/java/com/conveyal/r5/streets/StreetRouter.java
Which appeared in 70fc77c. P+R and bike sharing is working again.
Main source of troubles was in state creation from old state. Since first state had negative backEdges  (from setOrigins etc.) next state had those state as backState and there were troubles during path construction in response. Now state creation has backState only if those backState has positive backEdge.
And inside traverse a check needed to be changed from backEdge != -1 to backEdge >= 0 because otherwise we would get exception since first state can have negative edges.
With this changes there is no more negative edges in results.
There are lines [400](https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/streets/StreetRouter.java#L400) and [411](https://github.com/conveyal/r5/blob/master/src/main/java …
=> Should fix problem with negative edges

src/main/java/com/conveyal/r5/publish/StaticMetadata.java, src/main/java/com/conveyal/r5/publish/StaticServer.java, src/main/java/com/conveyal/r5/transit/TripPattern.java, src/main/java/com/conveyal/r5/transitive/TransitiveNetwork.java
I suspected the problem with zoomed-in transitive rendering in TAUI was bad geometries where shapes aren't present, as in Marseille. I did a bunch of refactoring to break the TransitiveNetwork down into functional units, and eventually noticed that we were using stop IDs as vertex IDs without the intermediate lookup.
Although the rendering is much better than it was (not jumping around to random street vertices) for some reason the results are still bizarre. The weirdness seems more common and visible on inter-city trains. Things render properly in schematic mode but the destination station seems to be shifted one stop early (while retaining the true destination stop's name) in geo-accurate mode. It seems plausible that I've introduced some off-by-one error when generating the geometries …
=> Refactor transitive network construction

.travis.yml, src/main/java/com/conveyal/r5/streets/StreetLayer.java, src/main/java/com/conveyal/r5/streets/TarjanIslandPruner.java, src/test/java/com/conveyal/r5/streets/StreetLayerTest.java
This finds all strong components, meaning one-way cul-de-sacs will be eliminated.
It also is applied to all modes, so car/bike islands will be eliminated as well.
Fixes #228 and fixes #27.
@abyrd if you can review that would be great, ideally we'd also try building an NL graph to make sure the algorithm is tractable on a larger graph.
@evansiroky just tagging you since you reported the original issue.
=> Replace island removal code with Tarjan's algorithm.

src/main/java/com/conveyal/r5/analyst/cluster/AnalystClusterRequest.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java, src/main/java/com/conveyal/r5/analyst/cluster/GenericClusterRequest.java, src/main/java/com/conveyal/r5/analyst/cluster/GridRequest.java, src/main/java/com/conveyal/r5/analyst/cluster/GridResultConsumer.java, src/main/java/com/conveyal/r5/publish/StaticComputer.java, src/main/java/com/conveyal/r5/publish/StaticMetadata.java, src/main/java/com/conveyal/r5/publish/StaticSiteRequest.java, src/main/java/com/conveyal/r5/streets/Split.java
Previously the side channel would only open for old-style analyst requests, meaning that single point jobs would not complete when a regional job was running on the same graph. This fixes that and also cleans up the auto-shutdown code.
=> handle high priority browsochrones requests via side channels.

pom.xml, src/main/java/com/conveyal/r5/analyst/broker/Broker.java, src/main/java/com/conveyal/r5/profile/ProfileRequest.java, src/main/resources/worker.sh
This just passes in a user data and can be used with a standard Amazon Linux AMI, e.g. `ami-e5083683` in `eu-west-1`.
H/T @dfconway for helping with the shell scripting.
=> Remove the custom AMI requirement

src/main/java/com/conveyal/r5/transit/TransportNetwork.java, src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java
Addresses #279.
This moves `TransportNetworkCache.scenarioNetworkCache` -> `TransportNetwork.scenarios` and adds a Guava loading cache with a configurable number of transport networks (defaults to 1).
This also adds support for a bucketFolder, so that r5 networks (+ scenarios and manifest files) can be stored in a "subdirectory" on s3.
=> Support multiple networks in TransportNetworkCache

pom.xml, src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java
Only changes are to utilize `BaseGTFSCache` instead of `GTFSCache` directly and the new `getFeed` method created in https://github.com/conveyal/gtfs-lib/pull/67.
=> Update r5 to use the latest gtfs-lib

src/main/java/com/conveyal/r5/analyst/WebMercatorGridPointSet.java, src/main/java/com/conveyal/r5/streets/LinkedPointSet.java
Addresses a small todo from 9083021, by allowing sub-grids (based on user-defined project bounds) to extend beyond base super-grids (based on TransportNetwork extents).
Not sure if the distance arrays should be filled with MAX_OFFSTREET_WALK_METERS or something else.
It might be good to eventually send warnings like at LOC 171 to the front-end, as is currently done for some modification warnings.
=> fix(pointsets) allow points outside base pointset

src/main/java/com/conveyal/r5/analyst/Grid.java
We're not using it anywhere else as it is better practice to throw an Exception and let the consumer deal with things like an HTTP exception.
The method already throws an IOException and this sorta fits that category so use that instead.
=> Remove Spark.halt

src/main/java/com/conveyal/r5/analyst/Grid.java
I've tried to follow some suggestions in the code related to #315, but it doesn't seem that this initial work actually speeds things up -- the geotools implementation of intersection may already do what I've tried to here.
Using Lists will require changes to AggregationAreaController and SeamlessCensusGridExtractor in analysis-backend (on the speedier-rasterization branch).
=> Speedier rasterization

pom.xml, src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java
Small bugfix (for #290).
Also bump version number (unrelated to this bugfix; should have been done on the previously merged speedier-rasterization branch)
=> Allow exact-times to be false

src/main/java/com/conveyal/r5/streets/LinkedPointSet.java
As discussed, jobs may be disaggregated over large blocks.  Consider the UPS Worldport:
=> fix(linking): increase linking limit to 1600 m

src/main/java/com/conveyal/r5/streets/EdgeStore.java, src/main/java/com/conveyal/r5/streets/TarjanIslandPruner.java
This PR addresses the original problem identified in #335 (though subsequent posts in that thread may be related to other issues).
Strong components ("islands") were being falsely identified for cars, resulting in edges being removed even though they were well connected to the whole network.
When looping through vertices, a boolean `everySuccessorExplored` is initialized as true.  Then, `if (discoveryIndex[toVertex] == -1) everySuccessorExplored[0] = false` resets this boolean to false if there are more successors to explore.  Previously, this was nested inside `if (discoveryIndex[toVertex] > discoveryIndex[vertex])`, which is often false because the `discoveryIndex` for each vertex is initialized as -1.  So a given vertex _v_ could be left with `everySuccessorExplored = true`, even if …
=> Island pruning

src/main/java/com/conveyal/r5/analyst/BootstrappingTravelTimeReducer.java, src/main/java/com/conveyal/r5/analyst/broker/Broker.java, src/main/java/com/conveyal/r5/analyst/broker/BrokerHttpHandler.java, src/main/java/com/conveyal/r5/analyst/broker/Job.java, src/main/java/com/conveyal/r5/analyst/cluster/GridResultAssembler.java, src/main/java/com/conveyal/r5/common/Util.java
This PR addresses conveyal/analysis-backend#79 and a major memory leak #318.
It changes the way the broker works, so that regional analyses are enqueued as a single template task that the broker expands into a set of tasks, one for each gridded origin point. Those all share references to any more complex data structures so they use a lot less memory. We've also gone back to workers fetching their scenarios from S3 instead of passing the full scenario text in the tasks.
We have been running this for about one day, and in that time have run quite a few very large regional analyses using this new code. Memory usage is drastically lower and does not expand over time.
Note that this *changes the HTTP API of the broker* and therefore using this new code as the analysis broker requires …
=> Reduce memory consumption in broker

src/main/java/com/conveyal/r5/analyst/scenario/AddTrips.java
This PR fixes a boolean check that was improperly inverted.
`firstDepartures` is null for a `PatternTimetable` if it is frequency based. So if `firstDepartures` is null, `transitLayers.hasFrequencies` should be set to true.
=> fix(add-trips): properly set transitLayer.hasFrequencies

.travis.yml, src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java, src/main/java/com/conveyal/r5/analyst/broker/Broker.java, src/main/java/com/conveyal/r5/analyst/broker/Job.java, src/main/java/com/conveyal/r5/analyst/cluster/JobSimulator.java, src/main/java/com/conveyal/r5/labeling/SpeedLabeler.java, src/main/java/com/conveyal/r5/labeling/TypeOfEdgeLabeler.java, src/main/java/com/conveyal/r5/streets/EdgeStore.java, src/main/java/com/conveyal/r5/streets/LinkedPointSet.java, src/main/java/com/conveyal/r5/streets/Split.java, src/main/java/com/conveyal/r5/streets/StreetLayer.java, src/main/java/com/conveyal/r5/streets/StreetRouter.java, src/test/java/com/conveyal/r5/streets/ReverseRoutingTest.java, src/test/java/com/conveyal/r5/streets/TurnCostCalculatorTest.java, src/test/java/com/conveyal/r5/streets/TurnRestrictionTest.java, src/test/java/com/conveyal/r5/streets/TurnTest.java
This pull request fixes some problems with car routing in Analysis that were encountered by Alex on the SBB project. The biggest one is that we weren't providing the on-street mode of travel to the linking method at the origin point, so it could link to roads that were not traversable by the chosen mode.
A more subtle problem for which we do not yet have a complete solution is that ways can have different permissions in different directions, the most obvious example being parallel one-way OSM ways making up "dual carriageways" and boulevards.
There are multiple possible approaches, e.g. linking only to ways that are traversable in both directions, or linking to ways that are traversable in at least one direction. The approach in this PR works better but could still use refinement over …
=> Fix car linking

src/main/java/com/conveyal/r5/streets/EdgeStore.java, src/main/java/com/conveyal/r5/streets/TravelTimeCalculator.java
Those are seconds, not milliseconds. My mistake, probably due to proximity to a variable ending in "ms", which means meters per second. (Code is correct.)
=> Change method name to correct unit.

src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java, src/main/java/com/conveyal/r5/analyst/cluster/PathWriter.java, src/main/java/com/conveyal/r5/multipoint/MultipointDataStore.java
Previously we were using the base `write` method which only wrote the first 8 bits of an integer
when we were expecting the full 32. This PR corrects the writing of those ints and adds two more items to the path file headers for clarity.
=> Correct write ints to OutputStreams

src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java, src/main/java/com/conveyal/r5/analyst/cluster/TimeGrid.java, src/main/java/com/conveyal/r5/multipoint/MultipointDataStore.java
Utilizes the changes made in #405 and addresses #404. Will require front-end changes in the Analysis UI and Taui to work with the new storage format.
Intellij automatically expanded the `import java.io.*;` on save...is that the style we use?
=> Invert time grid storage loop and explicitly use LittleEndianDataOutputStreams

src/main/java/com/conveyal/r5/analyst/Grid.java, src/main/java/com/conveyal/r5/util/ShapefileReader.java
We've had multiple instances of users locking up the server by uploading geometries that are too large.  These large geometries usually indicate data errors (e.g. features at null island) or incorrect projections.
This PR should help avoid locking up by throwing explicit exceptions if:
- The shapefile projection is unrecognized
- The area of the overall shapefile bounding box exceeds 250,000 sq. km.
- The area of any feature exceeds 0.01 sq. degrees.  The individual features are processed as WGS84, so to avoid doing a large number of transformations, I'm proposing to use an area limit in square degrees.  This should be fine unless we start doing accessibility analyses in Antarctica.
=> Limit shapefile size

src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java
Addresses #424 
We still don't have a good way of handling errors that arise in regional analyses.  I've had users request support when their analyses are stuck at 0, and I find basic bundle/scenario errors upon checking logs.
One option would be forcing users to "preflight" regional runs with a single-point request by disabling the "New Regional Analysis" button in the UI unless isochrones are shown.
=> Respond to single-point requests with scenario errors that arise

pom.xml, src/main/java/com/conveyal/r5/streets/StreetLayer.java
This PR addresses a previously identified TODO: giving a length to the edges that link newly created stops to the street network.  
Before this PR, these links were given a length of 1 mm.  In edge cases, this could shift the starting vertex of the street search to an unexpected location (see #422 )
=> Give link edges a length

src/main/java/com/conveyal/r5/analyst/Grid.java
We need a more generous upper bound, because we intend users to upload large features for aggregation areas.
=> Increase upper bound on shapefile feature size

src/main/java/com/conveyal/r5/profile/ProfileRequest.java, src/main/java/com/conveyal/r5/streets/LinkedPointSet.java, src/main/java/com/conveyal/r5/streets/StreetRouter.java
Relevant issues: #373, #422, #360 
The main change here is adding the time and distance required to reach the first vertex of the streetLayer.
This change will make a comment in Split more salient: 
>  We don't yet handle initial and final Splits on the same edge. This can be a problem for Analysis if your starting point is on a long road without intersections. Travel times to other points along that road would be measured by going to the end of the road and back.
We could consider using something like StreetLayer.getOrCreateVertexNear() to actually perform a split at the origin.
=> Splitting and linking fixes

src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java, src/main/java/com/conveyal/r5/analyst/cluster/TimeGrid.java
Adds the full profile request to the GeoTIFF metadata; it can be viewed with gdalinfo. Resulting TIFF files can still be read in QGIS (confirmed).
Example:
```
jentilly:r5 matthewc$ gdalinfo ~/Downloads/analysis-geotiff-T-0\ \(11\).geotiff 
...
Metadata:
AREA_OR_POINT=Area
TIFFTAG_IMAGEDESCRIPTION={
"type" : "TRAVEL_TIME_SURFACE",
"fromLat" : 42.35822296142578,
"fromLon" : -71.06211853027344,
"toLat" : 0.0,
"toLon" : 0.0,
"fromTime" : 25200,
"toTime" : 32400,
"walkSpeed" : 1.3888888,
"bikeSpeed" : 4.1666665,
"bikeTrafficStress" : 4,
"carSpeed" : 20.0,
"streetTime" : 90,
"maxWalkTime" : 20,
"maxBikeTime" : 20,
"maxCarTime" : 45,
"minBikeTime" : 10,
"minCarTime" : 10,
"date" : "2018-07-07",
"limit" : 0,
"accessModes" : "WALK",
"egressModes" : "WALK",
"directModes" : "WALK",
"transitModes" : …
```
=> burn analysis parameters into geotiff metadata, fixes #454.

.travis.yml, README.md, pom.xml
Sorry for the extra commits...  I branched off of master.
This PR updates maven-semantic-release to the latest version.  I refactored maven-semantic-release to act as a plugin to semantic-release since other semantic-release plugins also behave this way.  Also, I moved some stuff around in .travis.yml.  The installation of aws and semantic release now happen in before_script so that these items are cached.  Also, semantic-release is now ran before deploying to s3.  This way, when a new release is generated, that release will get uploaded to s3.  Finally, I also added an entry to the git-commit-id-plugin telling it to use lightweight tags because it looks like semantic release does not create annotated tags.
=> Semantic release fix

src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorkerController.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java, src/main/resources/worker.sh
Together with https://github.com/conveyal/analysis-backend/pull/191, addresses https://github.com/conveyal/analysis-backend/issues/182 by making workers tag themselves in the userData startup script.
Also updates shutdown behavior (in light of https://aws.amazon.com/blogs/aws/new-per-second-billing-for-ec2-instances-and-ebs-volumes/).  We should go over the initial shutdown check carefully to ensure workers won't shut down prematurely:
- If workers start polling before they have completed network building, they may consider shutting down before actually completely building a network.  
- Also, is it a problem that the UI now stops retrying requests after 5 minutes?  For example, a worker may take 6 minutes to build a graph, but if a user walks away from their computer, the worker might …
=> EC2 startup and shutdown behavior

.travis.yml
maven-semantic-release v4.1.x+ now includes a verify-conditions step that checks if the maven project seems to be setup to be able to release to maven central.
=> Update to version 4.1.x of maven-semantic-release

src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java, src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java, src/main/resources/worker.sh
https://github.com/conveyal/analysis-backend/issues/200 was a specific case of a more general problem -- scenarios not being applied for regional analyses.  Fixes:
Separately,
=> Regional patches

.travis.yml
Semantic-release v16 is going to have a breaking change that will make maven-semantic-release not work properly (see https://github.com/conveyal/maven-semantic-release/issues/10). Therefore this change preemptively fixes semantic-release to v15.x.x to prevent future breakage until maven-semantic-release can be updated to support semantic-release v16.
=> Pin semantic-release to v15

src/main/java/com/conveyal/r5/streets/LinkedPointSet.java, src/main/java/com/conveyal/r5/streets/Split.java, src/main/java/com/conveyal/r5/streets/StreetRouter.java
We've gone back and forth on whether the `distance0` and `distance1` values for splits (and in LinkedPointSet) should include the perpendicular (off-street) component as well as the parallel component (along the edge).  In #358, the perpendicular component was added to these values, but other parts of the code were not updated to reflect this change (leading to #509).
This PR keeps the distance along the edge separate from the distance to the edge.
=> Splitting fixes/refactors

src/main/java/com/conveyal/r5/analyst/PointSet.java, src/main/java/com/conveyal/r5/profile/PerTargetPropagater.java, src/main/java/com/conveyal/r5/streets/LinkedPointSet.java
This is for review only - do not merge this PR yet, as the solution to #503 may be related and may be included in this PR.
**Fix broken assumptions in LinkedPointSet constructor**
Recently we re-enabled some assertions in the LinkedPointSet constructor, checking that the supplied base base linkage is compatible with the linkage being constructed. With those assertions enabled, R5 throws an exception as soon as I do a single point search.
The initial failure is due to a check on the base street layer. That check just seems to have been expressed incorrectly. But another problem came to light: The part of the LinkedPointSet constructor that copies the linkages clearly assumes that the base point set and supplied point set are the same size (and says so in its comments). It appeared that …
=> Various fixes to PointSet Linking

src/main/java/com/conveyal/r5/analyst/scenario/AddTrips.java
The mode of travel for added trips (routes) still can't be set in the UI, but this change at least copies over the default value (bus) from the AddTrips modification class. This has been confirmed to work - when bus is deselected in the UI, added routes are not considered. It should suffice to include a mode property in the modification JSON.
I don't want to merge this right away because it will change behavior in a way that may surprise users - if they are used to turning off buses and still seeing their added routes.
=> Set route type from modifications

.travis.yml, src/main/java/com/conveyal/r5/analyst/NetworkPreloader.java, src/main/java/com/conveyal/r5/analyst/PointSet.java, src/main/java/com/conveyal/r5/analyst/WebMercatorGridPointSetCache.java, src/main/java/com/conveyal/r5/analyst/progress/NetworkPreloaderProgressListener.java, src/main/java/com/conveyal/r5/analyst/progress/NoopProgressListener.java, src/main/java/com/conveyal/r5/analyst/progress/ProgressListener.java, src/main/java/com/conveyal/r5/analyst/progress/Task.java, src/main/java/com/conveyal/r5/analyst/progress/TaskAction.java, src/main/java/com/conveyal/r5/analyst/progress/TaskExecutor.java, src/main/java/com/conveyal/r5/analyst/scenario/AddTrips.java, src/main/java/com/conveyal/r5/analyst/scenario/ModificationTypeResolver.java, src/main/java/com/conveyal/r5/api/util/LegMode.java, src/main/java/com/conveyal/r5/profile/PerTargetPropagater.java, src/main/java/com/conveyal/r5/streets/EgressCostTable.java, src/main/java/com/conveyal/r5/streets/LinkedPointSet.java, src/main/java/com/conveyal/r5/util/AsyncLoader.java
This PR fixes #540 (Build distance tables only for egress).
Recently we made it possible to use car or bicycle, rather than just walking, for egress from public transit. Egress from transit is "propagated" using precomputed cost tables, so we now make those cost tables for all modes used in a search, in case a mode is used for egress from transit.
However, building these cost tables is very time consuming, and not necessary for a mode that serves only for access to transit, or direct access to destinations, but not for egress. We needed to separate the concept of "linkage" from "cost tables", building linkages for all street modes in use (access, direct, and egress), but cost tables only for egress modes.
This PR makes those changes, defining a new class for EgressCostTables. The …
=> Only build cost tables on egress modes

.travis.yml, src/main/java/com/conveyal/r5/analyst/cluster/AnalystWorker.java
I thought this was already merged, but apparently I never opened the PR.
As of https://github.com/conveyal/analysis-backend/pull/238, the Broker triggers an error if this timeout is exceeded. I've seen cases where the worker stably handles complex analyses, but it needs more time than this cutoff.
We may want to set this to an even longer value (e.g. 55 seconds). I'm hesitant to set it beyond 60, where we might cause problems by inadvertently exceeding some opaque Apache HTTP defaults.
Fixes #519
=> Give workers longer to complete single-point task

.travis.yml, src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java
In half-headway mode, passengers should board a frequency entry half the headway after the later of:
* their earliest possible arrival at the stop (`earliestTime`)
* the earliest possible arrival at the stop of the frequency entry
At https://github.com/conveyal/r5/commit/523a7601ef2a2d9302d0f48dd7463f78b6a3a421#diff-1b10c1587ece1a5ee7a4ce929d4bbb82L742, I replaced the latter with the former. We need both (cf. the maximum used in the return of `getWorstCaseFrequencyDepartureTime`).
This likely explains the recent unexpected results in the Santiago research, where the half-headway results showed much lower travel times than the MC results. In half-headway mode, passengers could board later frequency entries (e.g. with faster, off-peak speeds) without having to wait for those entries to …
=> fix(half-headway): don't board before frequency entry starts

src/main/java/com/conveyal/r5/profile/PerTargetPropagater.java
The slowest part of accessibility analysis is often the "propagation" step where we extend the transit search results out to the destination grid cells. I noticed that we are performing division inside the tightest inner loop of the propagation, and it’s the same division operation at every iteration. By just moving the code block up outside the loop it halved the run time. This can reduce propagation time by about half.
Note this also allows us to always use a time-based egress limit, eliminating some code.
=> Optimize propagation to perform less division in tight loop

src/main/java/com/conveyal/r5/analyst/Grid.java, src/main/java/com/conveyal/r5/analyst/TravelTimeReducer.java
These changes were made during today's work session. We decided to exactly follow the standard definition of percentile to avoid any future confusion. Also added some comments based on our discussions about inclusive/exclusive comparisons when computing accessibility.
=> Revise definition of non-interpolated percentile

src/main/java/com/conveyal/r5/analyst/Grid.java, src/main/java/com/conveyal/r5/analyst/scenario/RoadCongestion.java
An instance of PreparedGeometryFactory was being used to create PreparedGeometries.
A separate instance of this factory was being created for each instance of Grid, rather than being created in a local variable or placed in a static field. Looking at the implementation of the factory (there is no Javadoc) it seems threadsafe so could be static, and seems trivial to construct so could also just be constructed quickly as a local variable.
However the implementation is strange in that it seems inherently static (the factory holds no state) but is not declared static. I think we don't need the factory at all since we know this is a polygon - we can just inline the branch of the factory's code that creates a prepared polygon.
=> refactor(Grid): remove PreparedGeometryFactory

src/main/java/com/conveyal/r5/analyst/LinkageCache.java, src/main/java/com/conveyal/r5/analyst/NetworkPreloader.java, src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalysisTask.java, src/main/java/com/conveyal/r5/analyst/cluster/RegionalTask.java, src/main/java/com/conveyal/r5/analyst/cluster/TravelTimeSurfaceTask.java, src/main/java/com/conveyal/r5/streets/EgressCostTable.java, src/main/java/com/conveyal/r5/streets/LinkedPointSet.java, src/main/java/com/conveyal/r5/streets/Split.java, src/main/java/com/conveyal/r5/streets/StreetRouter.java
Fixes #287
Consider an origin O and destination D linked to edge W-Z at split points X and Y:
```   
O   D
|   |    
W---X---Y-----Z
```
Previously, the travel time from O to D calculated by R5 would be too long, because it included required travel to one end of the edge (O-X-W-X-Y-D).  The change in this PR passes the origin split to LinkedPointSet::eval, allowing the calculation of the correct time (O-X-Y-D).
For analyses with cumulative-opportunity cutoffs shorter than the time to traverse an edge, and for analyses that use decay functions, this change will increase accessibility relative to past versions of R5.
=> Refinements: travel time for origin and destination on same edge, adjustable web Mercator zoom level

src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java, src/main/java/com/conveyal/r5/profile/RaptorState.java, src/main/java/com/conveyal/r5/transit/TripPattern.java
https://github.com/conveyal/r5/commit/4a3b115bfff49be13f49303ed0d3e571fd2f3c23 favors paths that reduce access and transfer time, addressing #638. Other commits on this PR address a few miscellaneous cleanup TODOs.
We should discuss the assertions.
Based on the way we iterate through trips, it appears we assume trips on a pattern do not overtake each other. We may want to add a note about that and other limitations in how we use GTFS (e.g. transfers, handling of exact_times) to the user manual.
=> Refine paths

src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java, src/main/java/com/conveyal/r5/analyst/scenario/PickupWaitTimes.java, src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java, src/main/java/com/conveyal/r5/profile/PerTargetPropagater.java, src/main/java/com/conveyal/r5/profile/ProfileRequest.java, src/main/java/com/conveyal/r5/streets/EgressCostTable.java, src/main/java/com/conveyal/r5/streets/LinkedPointSet.java, src/main/java/com/conveyal/r5/streets/StreetRouter.java
We implemented support for pickup-delay modifications in https://github.com/conveyal/r5/pull/537, using a couple phases of work. My commits through `2c8a110` focused on on-demand `BICYCLE_RENT`. Subsequent commits were focused on enabling `CAR` with options to specify service between certain "stop" polygons and "zone" polygons.
This PR harmonizes the approaches and addresses a number of outstanding tasks:
* https://github.com/conveyal/r5/commit/e8d5e7d0e4e4999353b0bf8121ddcd474faffe07 includes clarifying comments and a no-op refactor for clarity
* https://github.com/conveyal/r5/commit/aadb689faf9aac0623650ac95b2b5943fe6ac5fa applies `defaultWait` values specified in PickupDelay modifications
* https://github.com/conveyal/r5/commit/aadb689faf9aac0623650ac95b2b5943fe6ac5fa moves tracking of …
=> Propagation cleanup

src/main/java/com/conveyal/analysis/components/broker/Broker.java
These were previously used only in tests but will be used in auto shutdown checks.
=> synchronize reads from map to avoid concurrent modification

src/main/java/com/conveyal/analysis/AnalysisServerException.java
We were seeing `null` instead of more helpful error messages because the default `.getMessage()` returns `detailMessage` of the superclass rather than `message`
=> Return message for AnalysisServerException

src/main/java/com/conveyal/analysis/controllers/OpportunityDatasetController.java, src/main/java/com/conveyal/r5/analyst/FreeFormPointSet.java
Count field was not being checked during freeform upload. It appears like it was meant to be, but the id field was instead checked twice.
During form upload, if the name field did not exist it would throw an `AnalysisServerException` that was then caught and re-thrown but with a new message that was less specific and harder to decipher. This refactors the form to allow those exceptions to get thrown to the appropriate handler.
=> Minor fixes for bugs found when modifying Freeform pointset upload

src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java
Notes: 
- `analysis.complete` does not seemed to be set correctly, so until we fix that we shouldn't use it.
- Downloading locally does not currently work due to the `csv.gz` file type. That needs to be fixed in the File package.
- If we are storing the URLs we should be able to use them in the download endpoint right? Either way, what we store should be compatible with the `FileStorageKey` so that we don't need to manually create the URL in the controller and can just do something like `new FileStorageKey(config.resultsBucket(), analysis.resultStorage.get(resultType))`.
=> Fix getCsvResults end point

src/main/java/com/conveyal/analysis/results/MultiOriginAssembler.java, src/main/java/com/conveyal/r5/analyst/TravelTimeReducer.java, src/main/java/com/conveyal/r5/analyst/cluster/PathResult.java, src/main/java/com/conveyal/r5/profile/PerTargetPropagater.java, src/main/java/com/conveyal/r5/transit/path/PatternSequence.java, src/main/java/com/conveyal/r5/transit/path/RouteSequence.java, src/main/java/com/conveyal/r5/transit/path/StopSequence.java
- Path results now include rows for direct itineraries (e.g. walking without transit)
- Re-enables oneToOne CSV results (part of #650)
=> Further path cleanup

src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java, src/main/java/com/conveyal/r5/analyst/Grid.java, src/test/java/com/conveyal/r5/analyst/GridTransformWrapperTest.java
Fixes #676. After adding some tests on the GridTransformWrapper, this relaxes restrictions on the backend so analyses with multiple grids of varying extents can be created.
=> Allow creating regional analyses with different destination grid extents

.github/.kodiak.toml
The Kodiak check stalled on a recent PR, maybe because of configuration changes elsewhere. I turned off that status check on our r5 dev branch. Anyway we always expected this to become a standard Github feature, and indeed automerge now exists and is seamlessly integrated.
=> Remove Kodiak

src/main/java/com/conveyal/r5/analyst/WebMercatorExtents.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorkerTask.java, src/main/java/com/conveyal/r5/analyst/cluster/RegionalTask.java
This is a fix to be applied on top of the already-merged #684. In addition to that backend change, it turns out we also needed a worker-side change to tolerate GridTransformWrappers in a method that used to only look for Grids. I also revised some comments explaining what's going on when we wrap multiple Grids to give them identical extents.
I ran a manual test against this PR where I took random (2D gaussian) points around Portland and split them into two halves, east and west, overlapping somewhat in the middle. These files were added to the analysis-e2e Fixtures directory alongside others used in manual tests. I ran three regional analyses: one with both east and west pointsets selected, one with only east, and one with only west. The analysis with both pointsets selected will require …
=> Fix regional analysis with Grids of different extents

src/main/java/com/conveyal/r5/profile/RaptorState.java
In-vehicle times were being copied over to waiting times, probably due to a copy/paste error
=> Record correct waiting time in path results

src/main/java/com/conveyal/analysis/models/AdjustDwellTime.java, src/main/java/com/conveyal/analysis/models/AdjustSpeed.java, src/main/java/com/conveyal/analysis/models/Modification.java, src/main/java/com/conveyal/analysis/models/RemoveStops.java, src/main/java/com/conveyal/analysis/models/RemoveTrips.java, src/main/java/com/conveyal/analysis/models/Reroute.java, src/main/java/com/conveyal/r5/analyst/scenario/AdjustSpeed.java
This should fix  #687.
Currently marked as draft PR, a few tasks remain: 
@ansoncfit indicated that the failing case described in #687 is nondeterministic (as expected) and hard to reproduce on production. So we will keep an eye on the new warning output from adjust speed modifications during our next round of manual testing.
=> Preserve stop order in hops

src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java, src/main/java/com/conveyal/analysis/results/AccessCsvResultWriter.java
This fixes a null pointer reported by @ansoncfit. We were reading a field on the task before it was copied from the incoming analysisRequest.
=> Change initialization order for Taui site tasks

src/main/java/com/conveyal/analysis/results/MultiOriginAssembler.java
Workers write Taui results directly to S3, so no resultWriters are needed in the Broker's assembler.
=> Allow Taui analyses with no resultWriters

.github/workflows/cypress-integration.yml
This disables deduping UI requests that come from multiple components (the tests run faster than real world usage).
Specifically, Cypress tests failing with a "button still exists but expected not to" type error should now pass. On the region page it would load the regions, delete the region, confirm deletion, and reload the regions page very fast. If it was less than 2 seconds, the request would be deduplicated and the region would still appear.
=> Build with NEXT_PUBLIC_CYPRESS: true

.github/workflows/cypress-integration.yml, build.gradle, src/main/java/com/conveyal/analysis/components/Component.java, src/main/java/com/conveyal/analysis/components/TaskScheduler.java, src/main/java/com/conveyal/analysis/controllers/BundleController.java, src/main/java/com/conveyal/analysis/controllers/UserActivityController.java, src/main/java/com/conveyal/analysis/models/Bundle.java, src/main/java/com/conveyal/analysis/util/ProgressInputStream.java, src/main/java/com/conveyal/gtfs/GTFSFeed.java, src/main/java/com/conveyal/gtfs/model/Entity.java, src/main/java/com/conveyal/r5/analyst/progress/ApiTask.java, src/main/java/com/conveyal/r5/analyst/progress/NetworkPreloaderProgressListener.java, src/main/java/com/conveyal/r5/analyst/progress/NoopProgressListener.java, src/main/java/com/conveyal/r5/analyst/progress/ProgressInputStream.java, src/main/java/com/conveyal/r5/analyst/progress/ProgressListener.java, src/main/java/com/conveyal/r5/analyst/progress/Task.java, src/main/java/com/conveyal/r5/analyst/progress/TaskAction.java, src/main/java/com/conveyal/r5/analyst/progress/WorkProduct.java, src/main/java/com/conveyal/r5/analyst/progress/WorkProductType.java, src/main/java/com/conveyal/r5/util/ExceptionUtils.java
This is a revised version of the new user activity API created in #706. This takes in to account the discussion on #716 and in subsequent meetings. The API is now more clearly defined via model classes within `UserActivityController.java`. The title of tasks is now separate from their description, with the latter changing as work is done. Fine grained progress reporting on OSM and GTFS will be shown separately, reporting the percentage of each file that's been loaded.
The endpoint will now stop reporting on tasks after their DONE or ERROR state has been delivered to a UI at least once, and one minute has passed.
Any exceptions will be attached to the Task as well as the Mongo. A common code path will be factored out for this purpose (tied in with the workProduct information), but it works …
=> Revised Activity API

src/main/java/com/conveyal/analysis/models/Bundle.java
Includes the priority of the GTFS error in the error type summary. This is useful for showing emphasis in the user interface depending on the priority.
I included in the error type summary because it appears that all of the errors of the same type have the same priority, if that is wrong I will move it into the error summaries.
=> Add priority to GTFS error summaries

src/main/java/com/conveyal/analysis/models/Bundle.java, src/main/java/com/conveyal/gtfs/GTFSFeed.java, src/main/java/com/conveyal/gtfs/error/DateParseError.java, src/main/java/com/conveyal/gtfs/error/DuplicateKeyError.java, src/main/java/com/conveyal/gtfs/error/DuplicateStopError.java, src/main/java/com/conveyal/gtfs/error/DuplicateTripError.java, src/main/java/com/conveyal/gtfs/error/EmptyFieldError.java, src/main/java/com/conveyal/gtfs/error/EmptyTableError.java, src/main/java/com/conveyal/gtfs/error/GTFSError.java, src/main/java/com/conveyal/gtfs/error/GeneralError.java, src/main/java/com/conveyal/gtfs/error/MisplacedStopError.java, src/main/java/com/conveyal/gtfs/error/MissingColumnError.java, src/main/java/com/conveyal/gtfs/error/MissingShapeError.java, src/main/java/com/conveyal/gtfs/error/MissingTableError.java, src/main/java/com/conveyal/gtfs/error/NoAgencyInFeedError.java, src/main/java/com/conveyal/gtfs/error/NumberParseError.java, src/main/java/com/conveyal/gtfs/error/OverlappingTripsInBlockError.java, src/main/java/com/conveyal/gtfs/error/RangeError.java, src/main/java/com/conveyal/gtfs/error/ReferentialIntegrityError.java, src/main/java/com/conveyal/gtfs/error/ReversedTripShapeError.java, src/main/java/com/conveyal/gtfs/error/ShapeMissingCoordinatesError.java, src/main/java/com/conveyal/gtfs/error/TableInSubdirectoryError.java, src/main/java/com/conveyal/gtfs/error/TimeParseError.java, src/main/java/com/conveyal/gtfs/error/TimeZoneError.java, src/main/java/com/conveyal/gtfs/error/URLParseError.java, src/main/java/com/conveyal/gtfs/error/UnusedStopError.java
Add a specific `Priority` to each `GTFSError` subclass enforced through the constructor. This affects all of the "old" GTFS errors. I selected each error's `Priority` from the files themselves or from the `NewGTFSErrorType` enum that looked most closely related to it. 
If there are desired changes to the priority levels used, please feel free to change directly or to submit a suggested change inline.
Additionally, I've removed a thrown exception during pattern naming for when pattern has a stop that doesn't exist. A error will have already been recorded, so removing that exception allows the feed creation to complete and for those recorded errors to be displayed. If there's an alternative way of achieving the same behavior, I'm open to suggestions.
=> Add Priority to each GTFSError subclass

src/main/java/com/conveyal/analysis/models/Bundle.java, src/main/java/com/conveyal/gtfs/error/DateParseError.java, src/main/java/com/conveyal/gtfs/error/DuplicateKeyError.java, src/main/java/com/conveyal/gtfs/error/DuplicateStopError.java, src/main/java/com/conveyal/gtfs/error/DuplicateTripError.java, src/main/java/com/conveyal/gtfs/error/EmptyFieldError.java, src/main/java/com/conveyal/gtfs/error/EmptyTableError.java, src/main/java/com/conveyal/gtfs/error/GTFSError.java, src/main/java/com/conveyal/gtfs/error/GeneralError.java, src/main/java/com/conveyal/gtfs/error/MisplacedStopError.java, src/main/java/com/conveyal/gtfs/error/MissingColumnError.java, src/main/java/com/conveyal/gtfs/error/MissingShapeError.java, src/main/java/com/conveyal/gtfs/error/MissingTableError.java, src/main/java/com/conveyal/gtfs/error/NoAgencyInFeedError.java, src/main/java/com/conveyal/gtfs/error/NumberParseError.java, src/main/java/com/conveyal/gtfs/error/OverlappingTripsInBlockError.java, src/main/java/com/conveyal/gtfs/error/RangeError.java, src/main/java/com/conveyal/gtfs/error/ReferentialIntegrityError.java, src/main/java/com/conveyal/gtfs/error/ReversedTripShapeError.java, src/main/java/com/conveyal/gtfs/error/ShapeMissingCoordinatesError.java, src/main/java/com/conveyal/gtfs/error/TableInSubdirectoryError.java, src/main/java/com/conveyal/gtfs/error/TimeParseError.java, src/main/java/com/conveyal/gtfs/error/TimeZoneError.java, src/main/java/com/conveyal/gtfs/error/URLParseError.java, src/main/java/com/conveyal/gtfs/error/UnusedStopError.java
This fixes a bug where pre-existing gtfs MapDB files could not be read, because they contained serialized errors with a priority field. The changed class did not have this field, causing a failure. We could have deleted and rebuilt all these database files, but then they'd be unreadable by older workers. We could also save new and old formats under different file names, but introducing multiple file format versions doesn't seem worthwhile for such a trivial difference. In any case, all new GTFS MapDB files will have an empty errors table.
=> Restore priority field

src/main/java/com/conveyal/analysis/models/AnalysisRequest.java
Users are seeing index out of bounds exceptions if they request an analysis using a deleted scenario. This add's a check on the backend to surface a clearer error when this occurs.
A corresponding front end change set will attempt to address the issue on the client side also.
=> Add variant index check

src/main/java/com/conveyal/analysis/SelectingGridReducer.java, src/main/java/com/conveyal/analysis/controllers/OpportunityDatasetController.java, src/main/java/com/conveyal/analysis/models/AnalysisRequest.java, src/main/java/com/conveyal/analysis/persistence/AnalysisCollection.java, src/main/java/com/conveyal/analysis/persistence/AnalysisDB.java, src/main/java/com/conveyal/analysis/persistence/MongoMap.java, src/main/java/com/conveyal/r5/analyst/BootstrappingTravelTimeReducer.java, src/main/java/com/conveyal/r5/analyst/Grid.java, src/main/java/com/conveyal/r5/analyst/GridTransformWrapper.java, src/main/java/com/conveyal/r5/analyst/WebMercatorExtents.java, src/main/java/com/conveyal/r5/util/ShapefileReader.java, src/test/java/com/conveyal/r5/analyst/GridTest.java, src/test/java/com/conveyal/r5/analyst/GridTransformWrapperTest.java, src/test/java/com/conveyal/r5/analyst/network/GridSinglePointTaskBuilder.java
Changes in this PR:
* Store a reference to a `WebMercatorExtents` in grids, instead of inlining the fields
* Impose a limit on (grid size * number of attributes), to avoid exhausting memory (see #727)
* Check for duplicate attributes in shapefile upload
* Allow upload of CSV files with no numeric attributes
* Ignore .xml files in shapefile uploads (because users would occasionally upload .shp.xml files that would cause fail the `verifyBaseNamesSame` check)
* Fix a string equality check
* Clean up a few miscellaneous comments/imports
=> Grid cleanup

src/main/java/com/conveyal/analysis/components/broker/Broker.java, src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java, src/main/java/com/conveyal/analysis/results/TimeCsvResultWriter.java
Recently we saw dozens of messages from our production system like this:
```
[production] User null of null: Optional[java.lang.NullPointerException]
at unknown frame
```
The "at unknown frame" text is from our implementation, handling a case where Java just does not provide a stacktrace. It sometimes removes the stacktrace when it's already been provided: https://stackoverflow.com/a/3010106/778449. The true error was:
```
[production] User null of null: Optional[java.lang.NullPointerException]
at com.conveyal.analysis.results.TimeCsvResultWriter.checkDimension(TimeCsvResultWriter.java:36)
```
This error message is confusing because: 
1. No username and group are currently available in the CsvResultWriter where the error occurs.
2. The checkState call assumes that …
=> Clarify travel time CSV errors

src/main/java/com/conveyal/r5/analyst/NetworkPreloader.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorker.java, src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java
In common use cases this should cause egress tables to be calculated before we fire the HandleRegionalEvent and begin routing, allowing better tracking of whether workers are still in a slow preparation phase.
This patched version is currently the r5 dependency for the head of cluster. It was necessary to run a TAUI site and a regional analysis for the whole Netherlands using bicycle egress. Without this patch, the workers will all shut down except for the single point worker and regional job progress will be very slow.
Note that some proportion of workers may survive without this patch; the ones that shut down seem to be those that handle at least one task that never reaches transit and therefore wait to build egress tables until after they've handled a few regional tasks and lowered …
=> Apply egress table preload logic in regional tasks

.github/workflows/cypress-integration.yml, src/main/java/com/conveyal/analysis/AnalysisServerException.java, src/main/java/com/conveyal/analysis/components/HttpApi.java, src/main/java/com/conveyal/analysis/components/eventbus/ErrorEvent.java, src/main/java/com/conveyal/analysis/components/eventbus/ErrorLogger.java, src/main/java/com/conveyal/analysis/controllers/OpportunityDatasetController.java, src/main/java/com/conveyal/file/FileStorage.java, src/main/java/com/conveyal/file/LocalFileStorage.java
This PR makes two small changes: 
- When files are moved into storage they are set read-only at the filesystem level, precluding accidental corruption or deletion, for example of MapDB files (which after a recent change are also opened in read-only mode for good measure).
- Removes some repetitive code from HTTP server exception handling code, allowing FORBIDDEN and UNAUTHORIZED exceptions to be handled by the same method as all other exceptions, which in turn causes them to fire error events, making it possible to log or otherwise broadcast messages about these errors.
- Before review and merge, we should follow up with other planned changes to respondToException and ErrorEvent, to include the HTTP request path in the ErrorEvent and log it. Authentication code (cluster-specific) can then …
=> File and logging tweaks

analysis.properties.template, src/main/java/com/conveyal/analysis/BackendConfig.java, src/main/java/com/conveyal/analysis/components/HttpApi.java, src/main/java/com/conveyal/r5/point_to_point/PointToPointRouterServer.java
Per the discussion in #683 and #717, this makes the CORS headers sent by the backend configurable so they can be set to the specific origin where the frontend is hosted, rather than allowing CORS from any (potentially malicious) website to access the backend. The CORS headers are configured by a new `access-control-allow-origin` property in analysis.properties.
To preserve existing behavior, set `access-control-allow-origin=*`, although this isn't best practice and is a particular problem if authentication is disabled.
This supersedes #683 and conveyal/analysis-ui#1457.
=> Make CORS headers configurable

src/main/java/com/conveyal/analysis/models/AnalysisRequest.java, src/main/java/com/conveyal/analysis/models/RegionalAnalysis.java, src/main/java/com/conveyal/file/FileStorageFormat.java
Set the `task.scenarioId` properly. The immediate bug this fixes is that regional analysis scenario JSON files can be downloaded again. The details about why we went with this change can be found here: #765 
Also:
1. Add back the FileStorageFormat JSON.
2. Add suggestion about renaming the `RegionalAnalysis#request` parameter in the subsequent change.
=> Fix Download Scenario JSON

src/main/java/com/conveyal/analysis/components/broker/Broker.java, src/main/java/com/conveyal/analysis/results/GridResultWriter.java, src/main/java/com/conveyal/analysis/results/MultiOriginAssembler.java
This PR attempts to address issue #766. Although the only known effect was log noise, it isn't pleasant having a known race condition in this handler. This reverses the order of operations affecting the job and the resultAssembler, so there is a potential for side effects. An audit of the code doesn't turn up anything obvious but unless we see repeated instances of the log noise, we should probably defer this patch to a future release.
=> Eliminate race condition in broker

src/main/java/com/conveyal/analysis/WorkerConfig.java, src/main/java/com/conveyal/analysis/components/LocalWorkerLauncher.java, src/main/java/com/conveyal/analysis/models/AnalysisRequest.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorker.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorkerTask.java, src/main/java/com/conveyal/r5/analyst/cluster/ChaosParameters.java
This is motivated by testing #517 and #768.  This allows intentionally requesting workers to fail during regional processing by throwing exceptions, dropping tasks, or completely exiting the JVM. It would benefit from some refinements described in the Javadoc, but is definitely useable as-is. For now this only applies to regional analyses but would also make sense for testing single point analysis (with the difference that the starting task and failure percent should probably be ignored).
For example, to test reporting of exceptions on workers, in the request JSON you can add:
```
{
"injectFault": {
"failureMode": "THROW_EXCEPTION",
"message": "This is an exception.",
"failurePercent": 50,
"startingAtTask": 100
}
```
After handling 100 tasks the job should fail, reporting an exception …
=> Fault Injection ("Chaos Engineering")

src/main/java/com/conveyal/gtfs/model/Route.java, src/main/java/com/conveyal/r5/transit/TransitLayer.java
We used to record warnings for any route_type code over 7 seen in a GTFS feed. The values 11 and 12 have been officially added and we already can interpret TPEG codes up to 1500. Logic has been changed so this will all work with no errors.
It seemed potentially disruptive (and maybe unnecessary) to add separate enum values in our domain model for trolleybus and monorail, so I mapped them to BUS and RAIL.
=> Accept extended route_type codes and map them to modes enum

src/main/java/com/conveyal/analysis/controllers/BundleController.java
This is an initial response to #779. Certain exceptions are translated to GtfsErrors to prevent them from making the feed unusable.
=> Tolerate large GTFS geographic extents

src/main/java/com/conveyal/analysis/controllers/NetworkTileController.java, src/main/java/com/conveyal/r5/analyst/scenario/RasterCost.java, src/main/java/com/conveyal/r5/kryo/KryoNetworkSerializer.java, src/main/java/com/conveyal/r5/rastercost/CostField.java, src/main/java/com/conveyal/r5/rastercost/ElevationCostField.java, src/main/java/com/conveyal/r5/rastercost/ElevationLoader.java, src/main/java/com/conveyal/r5/rastercost/MinettiCalculator.java, src/main/java/com/conveyal/r5/rastercost/RasterDataSourceSampler.java, src/main/java/com/conveyal/r5/rastercost/SunCostField.java, src/main/java/com/conveyal/r5/rastercost/SunLoader.java, src/main/java/com/conveyal/r5/rastercost/ToblerCalculator.java, src/main/java/com/conveyal/r5/streets/MultistageTraversalTimeCalculator.java, src/main/java/com/conveyal/r5/streets/StreetRouter.java
This PR builds on #782, changing the way cost rasters are applied and how their parameters are interpreted. It is set to merge into that PR rather than dev. The changes in this PR were influenced by https://github.com/conveyal/r5/pull/782#discussion_r817434445. 
Instead of each cost applying to the output of the previous cost and potentially amplifying its effects, each cost is applied separately to the base traversal time of the edge, and all of these differential costs are added together.
In each CostField, the multipliers are now stored normalized to zero instead of one, i.e. a factor of zero means "no additional effect, don't change the base traversal time" and a factor of one means "add 1x the base traversal time", i.e. double the cost of traversing that edge. More importantly for …
=> Additive cost rasters, elevation cost bugfix

src/main/java/com/conveyal/r5/streets/EdgeStore.java, src/main/java/com/conveyal/r5/trove/TByteAugmentedList.java
When new edges are created at split points for transit stops, the new edges have flags and speeds copied from the original unsplit edge. The streetClass values should be copied in the same place, as proposed in this PR.
To test, check to make sure that streets don't switch to class 4 at transit stops. Before the fix:
Based on discussions, @abyrd added another change here, addressing an existing FIXME related to Trove lists for streetClasses and in/out angles.
=> Copy street class to split edges

src/main/java/com/conveyal/r5/analyst/scenario/IndexedPolygonCollection.java
Because of an apparent copy/paste mistake in our code, users will see a confusing error if they try to use a pickup delay geojson without `name` properties. This PR corrects the mistake, checking the `id` property in the appropriate place (and leaving the `name` property checks unchanged in the following lines).
=> Fix condition for logging IndexedPolygonCollection attribute type errors

src/main/java/com/conveyal/analysis/models/DataSourceValidationIssue.java
=> Bugfix: add zero-argument constructor to `DataSourceValidationIssues` for deserialization

src/main/java/com/conveyal/analysis/controllers/BundleController.java, src/main/java/com/conveyal/analysis/controllers/GtfsController.java, src/main/java/com/conveyal/gtfs/GTFSCache.java, src/main/java/com/conveyal/gtfs/GTFSFeed.java, src/main/java/com/conveyal/gtfs/error/ForbiddenFieldError.java, src/main/java/com/conveyal/gtfs/model/Calendar.java, src/main/java/com/conveyal/gtfs/model/CalendarDate.java, src/main/java/com/conveyal/gtfs/model/Entity.java, src/main/java/com/conveyal/gtfs/model/Stop.java, src/main/java/com/conveyal/gtfs/validator/PostLoadValidator.java
This PR contains first steps to address issue #803. The most visible immediate effect is that it avoids spatial index errors from feeds with stops that lack coordinates when generating GTFS vector tiles. The underlying change is gracefully tolerating GTFS feeds that use the pathway extensions, even where we don't yet use those nodes in routing.
The code is already in working condition, but we may want to add more validation or build a full routable model from the pathways in transfers.txt. That could be done in this PR or a subsequent one.
=> Handle GTFS feeds with pathway nodes

src/main/java/com/conveyal/analysis/datasource/derivation/AggregationAreaDerivation.java, src/main/java/com/conveyal/analysis/models/AggregationArea.java
Store the zoom level of each aggregation area in the database. It is currently only in the grid file itself and therefore we cannot search the database for aggregation areas by zoom level. 
There is work started on a [script](https://github.com/conveyal/ui/pull/1832) to find all aggregation area files, parse the zoom level and add it to the corresponding database entry.
=> Add zoom level to aggregation areas

src/main/java/com/conveyal/analysis/components/TaskScheduler.java, src/main/java/com/conveyal/analysis/controllers/UserActivityController.java
Allow users to manually clear a tasks. Additionally, increases the automatic purge time to 24 hours.
Corresponds to https://github.com/conveyal/ui/pull/1835 which greatly simplifies the client side logic for handling tasks.
=> Add an endpoint for deleting tasks

src/main/java/com/conveyal/analysis/datasource/derivation/AggregationAreaDerivation.java
This will help when searching through data groups. Note: since the data group doesn't have any properties itself it must be in the name.
=> Use the zoom level in aggregation area data group name

src/main/java/com/conveyal/r5/common/GeometryUtils.java
We had a longstanding 250k sq km limit on grids, and in #748 applied the same limit to GTFS and OSM. This limit is too strict; a few users have encountered the size error when building a network with previously uploaded OSM and the latest worker version.
I considered separate limits for grids (because the 250k limit was in place for a while) and network inputs, but I don't think the added conditionals are worth it.
We should test uploading a large (e.g. California-size) shapefile and converting it to a grid to ensure this works. I am less concerned about the network input files, because we did not have a limit on those until recently.
=> Increase limit on geographic extents for grids, OSM, and GTFS

src/main/java/com/conveyal/r5/streets/StreetLayer.java
This has been tested locally as described in my comments on issue #681. It doesn't solve the underlying problem but recovers from missing elements like many of the other `vertex == -1` checks in the turn restriction processing code.
=> handle missing restriction vertex, fixes #681

src/main/java/com/conveyal/r5/analyst/FreeFormPointSet.java
The record index starts at the first record, while the source CSV index starts at the header.
Also, switching to "near line x" instead of "on line x" for users who may be troubleshooting with spreadsheet software that uses 1-based indexing.
=> Fix off-by-one in CSV error message

src/main/java/com/conveyal/analysis/components/broker/Broker.java
When a regional analysis triggers a request to start spot instance workers, if the request would lead the total number of workers to exceed our configured limit (~6x higher on prod vs. staging), the request is totally ignored.
This PR changes that behavior and reduces the likelihood requests will be ignored:
* Reduces the number of instances requested for higher zoom and non-transit analyses
* Adds a backoff function (h/t Zeno's paradox) -- if we are halfway to the limit on the total number of workers, no more than half of the available remaining slots will be requested
Three additional refinements could be considered -- per-access group limits, further reducing the number of instances requested when analyses don't have frequency-based routes (we don't yet expose `hasFrequency()` in a …
=> Refine spot instance startup

src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorker.java, src/main/java/com/conveyal/r5/analyst/cluster/PathResult.java, src/main/java/com/conveyal/r5/analyst/cluster/PathResultSummary.java, src/main/java/com/conveyal/r5/transit/RouteInfo.java, src/main/java/com/conveyal/r5/transit/TransitLayer.java, src/main/java/com/conveyal/r5/transit/path/RouteSequence.java, src/test/java/com/conveyal/r5/analyst/network/SimpsonDesertTests.java
Returning raw path summary data for usage in the UI. Necessary for sorting and converting to other formats.
=> Path summaries: return raw data in JSON

src/main/java/com/conveyal/analysis/controllers/WorkerProxyController.java
=> WorkerProxyController: use the status code from the worker response

src/test/java/com/conveyal/r5/analyst/network/SimpsonDesertTests.java
We were using rounded values that were originally intended for human-readable display, then truncating them for comparison in a test. The combination was never really intentional. Switched to the testing-oriented array comparison with error tolerance.
=> Remove vestiges of human-readable display

build.gradle
I did a local build after wiping out my gradle caches directory and it didn't seem to fetch anything from jitpack that's not also on the maven central repo.
This repo was recently unavailable which broke our build. It seems like we don't actually need it.
=> Remove jitpack maven repo

src/main/java/com/conveyal/r5/analyst/scenario/AdjustSpeed.java, src/main/java/com/conveyal/r5/analyst/scenario/ModifyStreets.java, src/main/java/com/conveyal/r5/streets/EdgeStore.java, src/main/java/com/conveyal/r5/streets/EdgeTraversalTimes.java, src/main/java/com/conveyal/r5/streets/SingleModeTraversalTimes.java, src/test/java/com/conveyal/r5/analyst/scenario/ModifyStreetsTest.java
Some of the options for ModifyStreets modifications adjust generalized costs for walking and biking. These options would only work on special networks containing a special generalized costs data table that is not present by default in most networks. Those data tables are currently only created in networks built from very particular OSM data where every way has all of the special tags contributing to the LADOT generalized cost (com.conveyal.r5.streets.LaDotCostTags).
Some users have tried out the walk cost and bike cost ModifyStreets parameters and seen cryptic messages like "bikeGenCostFactor can only be set to values other than 1 on networks that support per-edge factors." Rather than keeping and repeatedly explaining this disappointing/confusing behavior, I decided to change the …
=> Add table of per-edge factors to network when modification requires it

src/main/java/com/conveyal/r5/analyst/scenario/ModifyStreets.java, src/main/java/com/conveyal/r5/analyst/scenario/ShapefileLts.java, src/main/java/com/conveyal/r5/labeling/LevelOfTrafficStressLabeler.java, src/main/java/com/conveyal/r5/shapefile/ShapefileMatcher.java, src/main/java/com/conveyal/r5/streets/EdgeStore.java, src/test/java/com/conveyal/r5/analyst/scenario/ModifyStreetsTest.java, src/test/resources/manual/README.txt
Add method that clears all LTS flags before setting a new one. This method is then used in ModifyStreets and ShapefileMatcher. Code comments have been clarified to avoid creating similar problems in the future.
Some refactoring was also done to improve readability (enum value imports and braces around conditional blocks).
This enforces certain behavior in Modifications. It is still possible for the LevelOfTrafficStressLabeler to set multiple flags during initial network build, though it seems to have been designed not to, and LTS data has always been set with this mechanism in the past.  Further checks and normalization should be added to always allow only a single LTS flag, at every place they are ever set. In theory this would be doing extra work. In practice it's a series of bitwise …
=> Avoid setting multiple LTS flags on edges via modifications

src/main/java/com/conveyal/r5/analyst/error/TaskError.java, src/main/java/com/conveyal/r5/analyst/scenario/AddStreets.java, src/main/java/com/conveyal/r5/analyst/scenario/AddTrips.java, src/main/java/com/conveyal/r5/analyst/scenario/AdjustDwellTime.java, src/main/java/com/conveyal/r5/analyst/scenario/AdjustFrequency.java, src/main/java/com/conveyal/r5/analyst/scenario/AdjustSpeed.java, src/main/java/com/conveyal/r5/analyst/scenario/Modification.java, src/main/java/com/conveyal/r5/analyst/scenario/ModifyStreets.java, src/main/java/com/conveyal/r5/analyst/scenario/PickupDelay.java, src/main/java/com/conveyal/r5/analyst/scenario/RasterCost.java, src/main/java/com/conveyal/r5/analyst/scenario/RemoveStops.java, src/main/java/com/conveyal/r5/analyst/scenario/RemoveTrips.java, src/main/java/com/conveyal/r5/analyst/scenario/Reroute.java, src/main/java/com/conveyal/r5/analyst/scenario/RoadCongestion.java, src/main/java/com/conveyal/r5/analyst/scenario/ShapefileLts.java, src/main/java/com/conveyal/r5/analyst/scenario/StopSpec.java, src/test/java/com/conveyal/r5/analyst/scenario/ModifyStreetsTest.java
Messages are added via a method only when set is below a certain size. If a set reaches the maximum size, a message is added explaining that some messages were omitted for brevity.
=> Limit number of error/warning/info messages

src/main/java/com/conveyal/analysis/components/broker/Broker.java, src/main/java/com/conveyal/r5/streets/StreetLayer.java
See discussion in comments on #841 and in code comments. Even when access=no|private, there are frequently exceptions for single modes. We want to default to the preexisting behavior of allowing passage (and rely only on edge traversal permissions) whenever we see exception tags that aren't clearly blocking access.
=> Single-mode exceptions in isImpassable / Limit launched workers to half of remaining capacity

src/main/java/com/conveyal/analysis/controllers/BrokerController.java, src/test/java/com/conveyal/analysis/controllers/ArgumentValidationTest.java
We used UUIDs without hyphens for a period in the past. This PR modifies the `BrokerController.checkUuid` method to allow those.
Migrating these IDs would be ideal. But migrating IDs is not simple. We have a bigger DB migration planned in the future and will migrate IDs to a single type then.
=> Allow UUIDs without hyphens

src/main/java/com/conveyal/r5/analyst/cluster/TransportNetworkConfig.java, src/main/java/com/conveyal/r5/streets/EgressCostTable.java, src/main/java/com/conveyal/r5/streets/LinkedPointSet.java, src/main/java/com/conveyal/r5/transit/TransitLayer.java, src/main/java/com/conveyal/r5/transit/TransportNetwork.java, src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java
This is a user-configurable version of [010970c](https://github.com/conveyal/r5/pull/786/commits/010970c6af2b7250b26290301ec338b48b848a23) in #786.
The user can add `"buildGridsForModes": ["BICYCLE", "CAR"]` to the TransportNetworkConfig to pre-build linkages and distance tables and serialize them in the network. This should alleviate the problem of hundreds of regional workers all building the same distance tables (though not during some scenario applications, which will require additional optimizations).
Currently there is no way to inject TransportNetworkConfig during a bundle upload. We must manually edit the network config JSON file on the backend server (in `~/cache/bundles/networkid.json`) and `aws s3 cp` to overwrite the copy on S3 before the network is built by a single point …
=> Pre-build linkages and egress tables for additional street modes via TransportNetworkConfig

.github/workflows/gradle.yml, build.gradle
This is an alternative approach to #866.
Updated build.gradle to use newer versions of plugins that are compatible with Gradle 8.x.
Also fixed deprecation warnings for Gradle 9.x and switched to gradle dependency caching built in to setup-java action.
See further discussion on https://github.com/conveyal/r5/pull/866#issuecomment-1469820507
I have tested all the build tasks we normally use.
=> Update build.gradle for gradle 8.x (and future 9.x)

build.gradle, src/main/java/com/conveyal/gtfs/GTFSFeed.java, src/main/java/com/conveyal/gtfs/error/DuplicateKeyError.java, src/main/java/com/conveyal/gtfs/error/MissingKeyError.java, src/main/java/com/conveyal/gtfs/model/Agency.java, src/main/java/com/conveyal/gtfs/model/Calendar.java, src/main/java/com/conveyal/gtfs/model/CalendarDate.java, src/main/java/com/conveyal/gtfs/model/Entity.java, src/main/java/com/conveyal/gtfs/model/FareAttribute.java, src/main/java/com/conveyal/gtfs/model/Route.java, src/main/java/com/conveyal/gtfs/model/Stop.java, src/main/java/com/conveyal/gtfs/model/StopTime.java, src/main/java/com/conveyal/gtfs/model/Trip.java
Addresses #792. A method is defined and applied for all entity types with simple string IDs, including stops and routes.
=> Check duplicate and missing GTFS entity keys

build.gradle, src/main/java/com/conveyal/analysis/models/AnalysisRequest.java, src/main/java/com/conveyal/gtfs/model/Pattern.java, src/main/java/com/conveyal/r5/analyst/Grid.java, src/main/java/com/conveyal/r5/analyst/WebMercatorExtents.java, src/main/java/com/conveyal/r5/util/EncodedPolylineSerializer.java, src/test/java/com/conveyal/r5/analyst/GridTest.java, src/test/java/com/conveyal/r5/analyst/network/GridSinglePointTaskBuilder.java, src/test/java/com/conveyal/r5/analyst/network/RandomFrequencyPhasingTests.java
Addresses issue #844. All Grid and WebMercatorExtents constructors / factory methods will now hit the zoom and extents checks. Tests updated to use acceptable zoom levels. Comments in code further explaining the approach.
As far as I know every place we use Grid and WebMercatorExtents is legitimately subject to these restrictions. We should think about whether there are legitimate places we need to use other zoom levels, though I think the cell-count restrictions would be valid everywhere (retina raster map tiles should never exceed 512x512).
If we used WebMercatorExtents to make map tiles for example, we'd need an exception to the zoom level restrictions, but our VectorMapTile class does not make use of WebMercatorExtents. As an aside, WebMercatorExtents contains its own methods for …
=> Always checkGridSize when creating grids

src/main/java/com/conveyal/analysis/controllers/UserActivityController.java
Handle the case when `taskScheduler.getTaskForUser` returns `null` so that we to prevent `NullPointerException`s which we've seen in the logs from time to time.
=> Fix an NPE when a task does not exist

build.gradle, src/main/java/com/conveyal/gtfs/model/Agency.java, src/main/java/com/conveyal/gtfs/model/Calendar.java, src/main/java/com/conveyal/gtfs/model/CalendarDate.java, src/main/java/com/conveyal/gtfs/model/Entity.java, src/main/java/com/conveyal/gtfs/model/FareAttribute.java, src/main/java/com/conveyal/gtfs/model/FareRule.java, src/main/java/com/conveyal/gtfs/model/FeedInfo.java, src/main/java/com/conveyal/gtfs/model/Frequency.java, src/main/java/com/conveyal/gtfs/model/Route.java, src/main/java/com/conveyal/gtfs/model/ShapePoint.java, src/main/java/com/conveyal/gtfs/model/Stop.java, src/main/java/com/conveyal/gtfs/model/StopTime.java, src/main/java/com/conveyal/gtfs/model/Transfer.java, src/main/java/com/conveyal/gtfs/model/Trip.java
Some error messages (particularly those produced in post-validation) had row numbers based on entity.sourceFileLine which is one-based, while others used raw zero-based row numbers.
In testing all sorts of error messages now appear to consistently match the line numbers shown in text editors.
=> Make all row numbers one-based for consistency

src/main/java/com/conveyal/analysis/models/ConvertToFrequency.java
This field is not used anywhere in R5 and will no longer be used in the UI. This corresponds to https://github.com/conveyal/ui/pull/1978.
=> Remove unused pattern trips field

src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java, src/main/java/com/conveyal/r5/analyst/TravelTimeReducer.java, src/main/java/com/conveyal/r5/analyst/cluster/RegionalTask.java, src/main/java/com/conveyal/r5/analyst/cluster/TravelTimeSurfaceTask.java, src/test/java/com/conveyal/r5/analyst/network/GridLayout.java, src/test/java/com/conveyal/r5/analyst/network/GridRegionalTaskBuilder.java, src/test/java/com/conveyal/r5/analyst/network/SimpsonDesertTests.java
This is a follow up to #896 that fixes #907. Explanation in comments on that issue #907.
This has been integrated into the 2023 fall release branch and tested as backend/worker v6.9-11-g679fd4b. So far it looks to be working correctly for single point requests both with and without destination grids supplied for accessibility calculations.
=> Use regional tasks in Simpson Desert tests

src/main/java/com/conveyal/r5/analyst/TemporalDensityResult.java
We decided our temporal density results have 120 columns (0 to 119). In the `TemporalDensityResult` constructor, the third dimension is 120:
`this.opportunitiesPerMinute = new double[destinationPointSets.length][nPercentiles][120]`
When recording results, opportunities should only be recorded if they are less than 120 minutes away, as proposed in this PR.
=> Prevent ArrayIndexOutOfBoundsException when recording TemporalDensityResult

src/main/java/com/conveyal/analysis/components/broker/Broker.java, src/main/java/com/conveyal/analysis/components/broker/Job.java, src/main/java/com/conveyal/analysis/components/eventbus/ErrorEvent.java, src/main/java/com/conveyal/r5/analyst/cluster/RegionalWorkResult.java, src/main/java/com/conveyal/r5/util/ExceptionUtils.java
This PR addresses problems discussed in #919 and #887. It makes two small changes, each of which alone would prevent the runaway error reporting observed on 2023-12-18 (EST). In addition it reduces the volume of errors sent and recorded.
=> Prevent runaway error reporting

src/main/java/com/conveyal/analysis/components/HttpApi.java, src/main/java/com/conveyal/analysis/components/eventbus/ErrorEvent.java, src/main/java/com/conveyal/analysis/results/MultiOriginAssembler.java, src/main/java/com/conveyal/r5/analyst/cluster/PathResult.java, src/main/java/com/conveyal/r5/util/ExceptionUtils.java
We currently limit the number of destinations and OD pairs in regional analyses with time/path results. This PR fixes a couple issues with the related guardrails:
- Fixes a conditional so that when `oneToOne = true`, the broker checks the number of OD pairs (which equals the number of origins) against the correct limit, rather than just allowing the analysis to proceed.
- Checks limit on number of destinations for path analyses in broker. Workers were applying a stricter limit (5000 destinations for path analyses) than the broker, so the broker could potentially enqueue millions of tasks that would trigger an immediate error once they reached the workers.
Small refactor for brevity/legibility: `task = job.templateTask`
=> Fix freeform guardrails

src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java, src/main/java/com/conveyal/analysis/persistence/MongoMap.java
This change adds a new helper method to pass a `fields` object to `MongoMap#findByIdIfPermitted` and utilizes that to exclude modifications while looking up a regional analysis to generate a `scenarioJsonUrl`.
This will prevent `JacksonDBDecoder` errors from occurring if custom modifications are used in a worker version that do not also exist in the server. Sample errors like:
```
java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:67)
at com.conveyal.analysis.persistence.MongoMap.findByIdIfPermitted(MongoMap.java:51)
```
=> Exclude modifications for regional analysis lookup

src/main/java/com/conveyal/r5/analyst/TravelTimeComputer.java
Addresses #764. Continuing routing on foot should only be necessary for searches that are trying to access transit stops. These searches also cover a smaller area than non-transit searches, so the final foot routing step is less time consuming.
=> keepRoutingOnFoot only in transit access searches

src/main/java/com/conveyal/analysis/models/AnalysisRequest.java, src/main/java/com/conveyal/analysis/models/CsvResultOptions.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorkerTask.java, src/main/java/com/conveyal/r5/analyst/cluster/PathResult.java, src/main/java/com/conveyal/r5/transit/TransitLayer.java, src/main/java/com/conveyal/r5/transit/path/RouteSequence.java
This makes it possible to represent stops and routes in CSV output using their names in addition to (or instead of) their IDs. Users have commented that they greatly prefer to work with the names, and often only with the names. Though they're not guaranteed to be unique, in some data sets names are clear enough to work well.
Showing route names has the additional major benefit of showing which modification created a route (instead of a meaningless UUID) in routes that did not come from GTFS.
As recently discussed, this also introduced a freeform `Set<String>` flags field in requests for enabling experimental, undocumented, or arcane behavior in backend or workers. When making a JSON request this will look like `"flags": ["csv_names", "csv_no_ids"]`. This should progressively replace all …
=> Include names in paths in CSV

src/main/java/com/conveyal/analysis/controllers/AggregationAreaController.java, src/main/java/com/conveyal/analysis/controllers/LocalFilesController.java, src/main/java/com/conveyal/analysis/controllers/OpportunityDatasetController.java, src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java, src/main/java/com/conveyal/analysis/results/BaseResultWriter.java, src/main/java/com/conveyal/file/FileStorage.java, src/main/java/com/conveyal/file/FileStorageFormat.java, src/main/java/com/conveyal/file/UrlWithHumanName.java
The backend returns download URLs as small JSON objects with a `url` property. In this PR, these JSON responses are extended to also have a humanName property, which is an alternate filename that is more human readable but not guaranteed to be unique. This enables #673 (as discussed in https://github.com/conveyal/r5/issues/673#issuecomment-1912000319) but should be backward compatible with existing UI as responses still have the same old `url` property. The new `humanName` property can be used in various ways such as the download attribute of an HTML link or as the attachment name in a content-disposition header.
Regional result CSV download links seem to be the odd one out: they return text/plain instead of a JSON wrapped URL. Switching them over to use JSON wrapped URLs like everything …
=> Make human-friendly names available and allow multi-grid downloads 

src/main/java/com/conveyal/analysis/components/BackendComponents.java, src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java, src/main/java/com/conveyal/r5/analyst/progress/Task.java
Discussion and observations at https://github.com/conveyal/r5/pull/932#issuecomment-2048894228.
It may be possible to make creation of single-cutoff geotiffs and grids faster (e.g. using NIO buffers). But for the time being it can take several minutes to produce and archive all the geotiffs for a single large regional analysis. This PR is a working proof of concept to perform this operation in the background. The process of making the zip file has been moved almost verbatim into a Task.withAction(). Usage:
```
> curl 'http://localhost:7070/api/regional/66179beec42a7657af4fdd2d/all' -v
HTTP/1.1 202 Accepted
"Building ZIP in background."
> curl 'http://localhost:7070/api/regional/66179beec42a7657af4fdd2d/all' -v
HTTP/1.1 202 Accepted
"ZIP is already being prepared in the background."
> curl …
```
=> Schedule creation of geotiff zip files in the background

src/main/java/com/conveyal/r5/analyst/cluster/RegionalTask.java
This PR adds a `flag` (`CROP_DESTINATIONS`) to crop destination grids to the web mercator extents used for origins. This setting can be useful for reducing computation, especially for auto analyses in large regions.
=> Add flag to crop regional analysis destinations to origin extents

build.gradle
This is the newest driver, but with an older ("legacy") programming API that matches our code. It should be a drop-in replacement, and our Mongojack dependency also seems to cooperate with this as its transitive mongodb driver dependency.
=> Update to latest mongodb legacy java driver

build.gradle, src/main/java/com/conveyal/r5/analyst/NetworkPreloader.java, src/main/java/com/conveyal/r5/analyst/cluster/ScenarioCache.java, src/main/java/com/conveyal/r5/analyst/cluster/WorkerStatus.java, src/main/java/com/conveyal/r5/streets/StreetRouter.java, src/main/java/com/conveyal/r5/transit/TransportNetwork.java, src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java, src/main/java/com/conveyal/r5/transit/TripPattern.java
When running regional analyses on a list of over 70 scenarios with bike egress on a large network with many transit stops (Netherlands), the workers eventually run out of memory and stall. This is because the linkages and egress tables for all these scenarios accumulate in memory and are never evicted.  This problem was not usually noticeable when people were running analyses one by one, but becomes apparent when using scripting tools to launch regional analyses for large numbers of slightly varying scenarios.
Here I have used a Caffeine LoadingCache to hold the scenario networks instead of a simple Map. This allows eviction of older items when the cache reaches a maximum size. It was a little tricky to locate all the scenario application logic in the right place together with the …
=> Application-wide, size-limited cache for scenario networks

src/main/java/com/conveyal/analysis/controllers/BundleController.java, src/main/java/com/conveyal/analysis/models/Bundle.java, src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java
This is a draft implementation of the server side of the functionality described in #644, as a basis for discussion on integration with the UI.
At bundle creation, the POST request body can now include a "config" item containing JSON that is deserialized to a `com.conveyal.r5.analyst.cluster.TransportNetworkConfig`. This deserialization step provides some free validation and fail-fast behavior if the user makes mistakes in crafting the network configuration. For backward compatibility, the OSM and GTFS ID fields of that `TransportNetworkConfig` object are ignored and overwritten with the ones specified in the enclosing POST form's other fields.
The completed network config is then included in the database entry for the bundle, as well as the JSON file in file storage that is visible to …
=> Store and retrieve user-specified network config, addresses #644

src/main/java/com/conveyal/r5/analyst/cluster/TransportNetworkConfig.java, src/main/java/com/conveyal/r5/kryo/KryoNetworkSerializer.java, src/main/java/com/conveyal/r5/labeling/SidewalkTraversalPermissionLabeler.java, src/main/java/com/conveyal/r5/streets/StreetLayer.java, src/main/java/com/conveyal/r5/transit/TransportNetwork.java, src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java
Users want the ability to configure different traversal permission labeling approaches (e.g., disallowing walking on any links that allow driving, under the assumption complete and separate sidewalk networks are available, see https://github.com/conveyal/r5/issues/643) 
This PR should be considered together with #941. Together with those changes, this PR allows users to build networks using a new experimental `SidewalkTraversalPermissionLabeler` with stricter walking permissions that are likely to be appropriate as more complete sidewalk networks become available.
Based on discussions in a work session a couple months ago, this PR removes the `buildNetworkFromBundleZip` method that has been unsupported since 2016.
This PR partly addresses https://github.com/conveyal/r5/issues/751 by …
=> Add custom walking traversal permissions via TransportNetworkConfig

src/main/java/com/conveyal/analysis/controllers/BundleController.java
When retrieving the config, return a clearer error if the file cannot be found so that can be handled individually.
=> Check if the bundle config exists, return 404 if missing

build.gradle, src/main/java/com/conveyal/analysis/controllers/BundleController.java, src/main/java/com/conveyal/analysis/models/Bundle.java, src/main/java/com/conveyal/r5/analyst/NetworkPreloader.java, src/main/java/com/conveyal/r5/analyst/cluster/ScenarioCache.java, src/main/java/com/conveyal/r5/analyst/cluster/TransportNetworkConfig.java, src/main/java/com/conveyal/r5/analyst/cluster/WorkerStatus.java, src/main/java/com/conveyal/r5/labeling/SidewalkTraversalPermissionLabeler.java, src/main/java/com/conveyal/r5/streets/StreetLayer.java, src/main/java/com/conveyal/r5/streets/StreetRouter.java, src/main/java/com/conveyal/r5/transit/TransportNetwork.java, src/main/java/com/conveyal/r5/transit/TransportNetworkCache.java, src/main/java/com/conveyal/r5/transit/TripPattern.java
- #940 
- #941 
- #942 
- #943 
- #944
=> v7.3 Release

src/main/java/com/conveyal/r5/analyst/LinkageCache.java, src/main/java/com/conveyal/r5/analyst/NetworkPreloader.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorker.java
This is a pure documentation change, fixing some obsolete information I noticed during a recent call.
The final block of documentation in the changeset was changed only for consistency with surrounding comments. It will take longer to work through the open questions in that block and verify current behavior. That would be useful, but I don't think I will reach reliable conclusions on that part by the time we do the release.
=> Update javadoc to reflect recent LinkageCache changes

src/main/java/com/conveyal/r5/analyst/NetworkPreloader.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorker.java, src/main/java/com/conveyal/r5/util/AsyncLoader.java
This PR fixes #949, a longstanding issue (possibly since #746).
We have two pathways for loading transport network data on a worker: `preloadData` (asynchronously, for single-point tasks) and `synchronousPreload` (for regional tasks). Once data are loaded in an AsyncLoader, they should be marked with `Status.PRESENT`. The async pathway was doing this correctly. But once a worker switched to a regional task, it would switch the status to `LOADING` and never switch it back to `PRESENT`.
This PR factors out a `setComplete` method and calls it in both pathways.
=> Set Status.PRESENT after synchronous preload

src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java, src/main/java/com/conveyal/analysis/models/RegionalAnalysis.java, src/main/java/com/conveyal/r5/analyst/cluster/RegionalTask.java
Remove old fields in regional analysis that haven't been used in many years. 
#957, which contains a MongoDB migration to clean up old regional analyses, should be merged and ideally run first.
We recently removed a similar worker version related flag from the UI here: https://github.com/conveyal/ui/pull/2064
=> Refactor: Remove deprecated / unused regional analysis fields

src/main/java/com/conveyal/analysis/controllers/RegionalAnalysisController.java, src/main/java/com/conveyal/r5/analyst/TemporalDensityResult.java, src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorkerTask.java, src/main/java/com/conveyal/r5/analyst/cluster/RegionalWorkResult.java
Add a dual access threshold validation check similar to cutoffs and percentiles when `includeTemporalDensity` is enabled while creating a regional analysis. 
After the changes in https://github.com/conveyal/r5/pull/955, we now require `dualAccessThresholds` to be set for both CSV and gridded results. Previously we used a `int dualAccessibilityThreshold` value for CSV results, but now the UI will send an array of thresholds for either CSV or gridded results to be used as the threshold. This PR also moves up the `SemVer` check to enforce users to use v7.4 and up if they want any kind of temporal density result. Otherwise, we would need to handle backwards compatibility with the old parameter on R5 versions >= v7 and < v7.4.
Generating temporal density results does not require a threshold to …
=> Validate dual access thresholds

src/main/java/com/conveyal/analysis/results/CsvResultWriter.java, src/main/java/com/conveyal/analysis/results/TemporalDensityCsvResultWriter.java
This PR modifies `CsvResultWriter` to set `this.task` before calling `columnHeaders` and changes `TemporalDensityCSVResultWriter` to use `dualAccessThresholds` directly from the regional task. The previous `columnHeaders` changes were attempting to access `dualAccessThresholds` before they were set which caused an NPE.
As previously noted in comments about `columnHeaders` there is probably a better solution that should be explored in the future.
=> Temporal CSV Fix
